export const CHANGE_CATEGORY = "CHANGE_CATEGORY"
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS"

export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS"
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS"
export const UPDATE_PRODUCT_SUCESS = "UPDATE_PRODUCT_SUCESS"

export const ADD_TO_CART = "ADD_TO_CARD"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"